### ISSUE TITLE
听歌成功后显示今天已播放0首

### ISSUE THREAD

**Issue by kirbystudy** [GustinLau/netease-cloud-node#2]
![image](https://user-images.githubusercontent.com/63231787/169700063-c475a638-b96c-438c-aae5-a3f4df86ca56.png)

**Comment by GustinLau** [comment]
有可能是当天听歌量已经到300首，听歌量没有增加的缘故，第二天再执行应该就可以了。

**Comment by kirbystudy** [comment]
我第一次运行的时候显示歌曲已听82首，然后第一次听歌完成后，直接就显示已听完300首歌。然后第二次运行就显示歌曲已听0首

**Comment by GustinLau** [comment]
网易云音乐一天最多能增加300首听歌量，听歌量大于300后当天后续不再增加听歌量。
脚本显示的播放数量其实是听歌量增加的数量，数量达300后，增量为0，所以显示播放0首。
脚本运行后可以到网易云音乐客户端查看升级进度，看是否有增加。

**Comment by kirbystudy** [comment]
![image](https://user-images.githubusercontent.com/63231787/169737813-7239de2f-c1cf-4d87-bab6-34a40d1962ee.png)
今天第一次运行的也是这样子。到第二首歌听歌成功后，就显示今天已播放300首。

**Comment by GustinLau** [comment]
脚本是调用网易云听歌完成接口，一次批量传入多首歌的ID，尽可能快的完成当天300首歌的播放量，并非一首一首的去调用。
听歌逻辑可以查看`api/index.js`里面的[`listen`](https://github.com/GustinLau/netease-cloud-node/blob/main/src/api/index.js#L183)方法，每次听歌实际上每次一执行听歌方法，是传了1000首歌的信息到接口，1000首歌中调用完毕后如果未满足每日300首歌的目标，会循环调用，代码中设置是最多10次，如果10次都未完成目标，则会结束听歌任务，如果10次过程中累计听歌300首，后续再调用接口也没用任何意义，也会结束听歌任务。

**Comment by kirbystudy** [comment]
懂了。就是批量获取歌曲的id进行播放，怪不得这么快就完成了！

**Comment by kirbystudy** [comment]
谢谢大佬的耐心指导，感谢感谢！
